### ISSUE TITLE
How to override some generators for ScalaCheck to force to (automatically) generate refined types? Non empty lists only, for example

### ISSUE THREAD

**Issue by kell18** [mrdziuban/scalacheck-magnolia#1]
Hello! 
Given quite a big structure of case classes and somewhere deep inside this structure I have fields which I want to refine, for example, make lists non-empty. Is it possible to tell ScalaCheck to make those lists non-empty using automatic derivation from scalacheck-magnolia project (without providing each field specifically)? Example:
```scala
import com.mrdziuban.ScalacheckMagnolia.deriveArbitrary
import org.scalacheck.Arbitrary
import org.scalacheck.Gen

case class A(b: B, c: C)
case class B(list: List[Long])
case class C(list: List[Long])

// I've tried:
def genNEL[T: Gen]: Gen[List[T]] = Gen.nonEmptyListOf(implicitly[Gen[T]])
implicit val deriveNEL = Arbitrary(genNEL)

implicit val deriveA = implicitly[Arbitrary[A]](deriveArbitrary)
```
But it's didn't worked out.

(original [question on SO](https://stackoverflow.com/questions/55398947/how-to-override-some-generators-for-scalacheck-to-force-to-automatically-gener))

Thank you!

**Comment by mrdziuban** [comment]
Hi @kell18, sorry I somehow missed this until over 3 years later! You can accomplish this like so ([scastie](https://scastie.scala-lang.org/mrdziuban/GHjt0EyNTlunqk49iemUbw/6))

```scala
import com.mrdziuban.ScalacheckMagnolia.deriveArbitrary
import org.scalacheck.{Arbitrary, Gen}

case class A(b: B, c: C)
case class B(list: List[Long])
case class C(list: List[Long])

implicit def genNEL[T: Arbitrary]: Arbitrary[List[T]] =
  Arbitrary(Gen.nonEmptyListOf(Arbitrary.arbitrary[T]))

deriveArbitrary[A].arbitrary.sample.get
```

I think your code is not working properly because `implicit val deriveNEL` is calling `genNEL` with no type parameter, so its type is `Arbitrary[List[Nothing]]`.

I'm archiving this repository, so also closing this issue. I encourage you to check out [`magnolify-scalacheck`](https://github.com/spotify/magnolify) for an updated library that supports scalacheck derivation.
